### ISSUE TITLE
editing devices fails

### ISSUE THREAD

**Issue by realies** [vinceh121/gmcserver#43]
```json
{"status":400,"description":"Invalid model","extras":null}

**Comment by vinceh121** [comment]
I should allow a 0-length model.

Related lines:
https://github.com/vinceh121/gmcserver/blob/4a9d267441186f2a624e5b39646213b5ea6e14e6/gmcserver-server/src/main/java/me/vinceh121/gmcserver/modules/DeviceModule.java#L170
